"""Complete current document topology, not upstream scientific or release admission.

The earlier three-include/one-external-figure document consumers remain unchanged.
This explicit successor includes every exact/control table and both observed maps,
while preserving their abstract, page, font, source, and no-pending requirements.
"""
from __future__ import annotations

import hashlib
import os
from pathlib import Path
import re
import subprocess

from embed_optim import paper_audit as original_audit
from embed_optim import paper_layout as original_layout
from embed_optim import primary_v3_manuscript as original
from embed_optim import primary_v3_manuscript_build as original_build
from embed_optim.primary_contract import file_identity, require_same, verify_file
from embed_optim.primary_v3_validation_io import write_new

RESULT_FILES = (
    'generated/optimizer-primary.tex',
    'generated/dimension-utilization.tex',
    'generated/recipe-sensitivity.tex',
    'generated/state-operator-factorial.tex',
)
EXTERNAL_FIGURES = (
    'figures/optimizer-weight-dimension-map.pdf',
    'figures/weight-to-retrieval-map.pdf',
    'figures/full-rate-retrieval-trajectories.pdf',
)
BUILD_INPUTS = ('main.tex', 'results.tex', *RESULT_FILES, 'references.bib',
                'vendor/acl.sty', 'vendor/acl_natbib.bst', *EXTERNAL_FIGURES)
TEX_INPUTS = set(BUILD_INPUTS) - {'references.bib', 'vendor/acl_natbib.bst'}
MAIN_LABELS = ('fig:weight-space-map', 'tab:optimizer-primary',
               'fig:observed-weight-retrieval', 'fig:dimension-utility')
APPENDIX_LABELS = ('tab:corrected-bridge', 'tab:exact-geometry-sensitivity',
    'tab:dimension-utilization', 'tab:weight-recipe-sensitivity',
    'tab:functional-recipe-sensitivity', 'tab:state-operator-factorial',
    'tab:claim-firewall', 'fig:all-rate-retrieval-trajectories')
CONTROL_MACROS = ('RecipeSensitivityFinding', 'WeightRecipeSensitivityTable',
                  'FunctionalRecipeSensitivityTable')


def need(value, message):
    if not value:
        raise ValueError(message)


def inspect_sources(root, expected_includes, constants):
    root = original.ordinary(root, directory=True)
    paper = original.ordinary(root / 'paper', directory=True)
    require_same(sorted(expected_includes), sorted(RESULT_FILES))
    expected = {'results.tex': constants, **expected_includes}
    need(all(type(value) is bytes for value in expected.values()), 'Fresh generated bytes required')
    paths = {name: original.ordinary(paper / name) for name in BUILD_INPUTS}
    bindings = {name: file_identity(path) for name, path in paths.items()}
    texts = {}
    for name in ('main.tex', *expected):
        raw = paths[name].read_bytes()
        need(name not in expected or raw == expected[name], 'Generated evidence differs: ' + name)
        texts[name] = original_audit._strip_latex_comments(raw.decode('utf-8'))
    main = texts['main.tex']
    need(not original.definitions(main) and not re.search(r'\\let(?![A-Za-z@])', main),
         'Main text may not redefine generated findings')
    need(tuple(m[2] for m in original.INPUT.finditer(main)) ==
         ('results', *(name.removesuffix('.tex') for name in RESULT_FILES)),
         'Complete current input topology differs')
    need(not re.search(r'\\(?:input|include)(?![A-Za-z@])', original.INPUT.sub('', main)),
         'Indirect or unbraced document input')
    need(original.INCLUDEGRAPHICS.findall(main) == list(EXTERNAL_FIGURES),
         'Complete current external figure topology differs')
    need(original_audit._paper_main_topology_complete(root), 'Original scientific section order differs')
    # New control material must remain between the original bridge and factorial,
    # with the two full comparison tables in the appendix; not hidden or uncalled.
    positions = [main.find(token) for token in (
        r'\DimensionRetrievalBridgeFinding', r'\RecipeSensitivityFinding',
        r'\StateOperatorMechanismFinding', r'\appendix',
        r'\WeightRecipeSensitivityTable', r'\FunctionalRecipeSensitivityTable',
        r'\StateOperatorAppendixTable')]
    need(all(pos >= 0 for pos in positions) and positions == sorted(positions),
         'Complete exploratory result ordering differs')
    need(all(len(re.findall(r'\\' + name + r'(?![A-Za-z@])', main)) == 1
             for name in CONTROL_MACROS), 'Missing or duplicated control finding/table')
    for name, text in texts.items():
        need(r'\ResultPending' not in text and not re.search(r'\b(?:PENDING|TODO|TBD)\b', text),
             'Unresolved active manuscript finding: ' + name)
        for label, pattern in original_audit.MANUSCRIPT_ENGINEERING_PATTERNS.items():
            need(not pattern.search(text), 'Implementation narrative: ' + label)
        inspected = original.INPUT.sub('', text) if name == 'main.tex' else text
        need(not original.FORBIDDEN_CONTROL.search(inspected), 'Unsafe or indirect manuscript control')
        need(name == 'main.tex' or not original.INCLUDEGRAPHICS.search(text),
             'Generated include cannot add an unbound external figure')
    requirements = {**original.RESULT_MACROS, RESULT_FILES[2]: CONTROL_MACROS}
    for name, required in requirements.items():
        macros = original.definitions(texts[name])
        for macro in required:
            values = macros.get(macro, [])
            wrapped = macro in {'CorrectedGeometryBridgeFinding', 'CorrectedGeometryBridgeTable'}
            need(len(values) == (2 if wrapped else 1)
                 and all(v['arity'] == 0 and v['body'].strip() for v in values)
                 and values[0]['kind'] == r'\newcommand'
                 and (not wrapped or values[1]['kind'] == r'\renewcommand'),
                 'Absent, empty, parameterized or redefined result macro: ' + macro)
    values = original.definitions(texts['results.tex'])
    require_same(sorted(values), sorted(original.CONSTANTS))
    for name, value in original.CONSTANTS.items():
        require_same(values[name], [{'kind': r'\newcommand', 'arity': 0,
                                    'body': f'{value:,}'.replace(',', '{,}')}])
        need(all(name not in original.definitions(text) for path, text in texts.items()
                 if path != 'results.tex'), 'Constant redefined outside clean constants file')
    abstract = original.abstract_readout(main, [texts[name] for name in RESULT_FILES])
    conservative = original_audit._abstract_word_budget(root)
    need(conservative['complete'], 'Original conservative abstract reserve fails')
    for name, path in paths.items():
        verify_file(path, bindings[name])
    return {'scope': 'current_dense_complete_document_component_v1', 'inputs': bindings,
        'actual_abstract': abstract, 'conservative_abstract_budget': conservative,
        'expected_generated_sha256': {name: hashlib.sha256(raw).hexdigest() for name, raw in expected.items()},
        'upstream_scientific_admission_performed': False, 'final_release_verified': False}


def caption_inventory(aux, main_end_page, pdf_pages):
    observed = {'figure': [], 'table': []}
    for match in re.finditer(r'\\@writefile\{(lof|lot)\}', aux):
        body, _ = original.brace_group(aux, match.end())
        prefix = re.match(r'\\contentsline\s*', body)
        need(prefix is not None, 'Malformed compiled caption')
        kind, pos = original.brace_group(body, prefix.end())
        caption, pos = original.brace_group(body, pos)
        page, _ = original.brace_group(body, pos)
        numberline = re.match(r'\\numberline\s*', caption)
        need(kind == {'lof': 'figure', 'lot': 'table'}[match[1]] and numberline is not None,
             'Compiled caption kind differs')
        number, _ = original.brace_group(caption, numberline.end())
        need(all(x.isascii() and x.isdecimal() for x in (number, page)), 'Invalid caption number/page')
        number, page = int(number), int(page)
        need(number > 0 and 1 <= page <= pdf_pages, 'Caption outside current PDF')
        observed[kind].append({'number': number, 'page': page, 'caption_tex': caption})
    require_same([r['number'] for r in observed['figure']], list(range(1, 5)))
    require_same([r['number'] for r in observed['table']], list(range(1, 10)))
    need(all(r['page'] <= main_end_page for r in observed['figure'][:3])
         and observed['figure'][3]['page'] > main_end_page, 'Figure in wrong document region')
    need(observed['table'][0]['page'] <= main_end_page
         and all(r['page'] > main_end_page for r in observed['table'][1:]),
         'Table in wrong document region')
    return observed


def layout(paper, pdf_pages):
    aux_path = original.ordinary(paper / 'build/main.aux')
    aux = aux_path.read_text()
    main_end = original_layout._page_for_unique_label(aux, original_layout.MAIN_END_LABEL, aux_path)
    need(1 <= main_end <= original_layout.DEFAULT_MAX_MAIN_PAGE, 'Main text exceeds unchanged eight pages')
    require_same(sorted(original_layout._observed_float_labels(aux)), sorted((*MAIN_LABELS, *APPENDIX_LABELS)))
    main = {name: original_layout._page_for_unique_label(aux, name, aux_path) for name in MAIN_LABELS}
    appendix = {name: original_layout._page_for_unique_label(aux, name, aux_path) for name in APPENDIX_LABELS}
    need(all(1 <= page <= main_end for page in main.values()), 'Main label outside main paper')
    need(all(main_end < page <= pdf_pages for page in appendix.values()), 'Appendix label outside appendix')
    return {'main_end_page': main_end, 'max_main_page': original_layout.DEFAULT_MAX_MAIN_PAGE,
        'main_float_pages': main, 'appendix_float_pages': appendix,
        'all_captions': caption_inventory(aux, main_end, pdf_pages)}


def recorded_inputs(paper, text):
    need([line for line in text.splitlines() if line.startswith('PWD ')] == ['PWD ' + str(paper)],
         'Compiler did not run in the fresh document directory')
    selected, systems, generated = {}, {}, set()
    for line in text.splitlines():
        if not line.startswith('INPUT '):
            continue
        path = Path(line[6:])
        if not path.is_absolute():
            path = paper / path
        resolved = path.resolve(strict=True)
        if resolved.is_relative_to(paper):
            name = resolved.relative_to(paper).as_posix()
            original.ordinary(path)
            if name in TEX_INPUTS:
                selected[name] = file_identity(path)
            elif name in {'build/main.aux', 'build/main.out', 'build/main.bbl'}:
                generated.add(name)
            else:
                raise ValueError('Undeclared local compiler dependency: ' + name)
        elif any(resolved.is_relative_to(root) for root in original_build.SYSTEM_TEX_ROOTS):
            need(resolved.is_file(), 'Invalid system TeX dependency')
            systems[str(resolved)] = file_identity(resolved)
        else:
            raise ValueError('Undeclared external compiler dependency')
    require_same(sorted(selected), sorted(TEX_INPUTS))
    need(bool(systems) and 'build/main.bbl' in generated, 'Incomplete source/bibliography recorder')
    return {'document': selected, 'system': systems, 'generated': sorted(generated)}


def compile_fresh(root, expected_includes, constants):
    """No prior build files, old audit patching, or upstream success arguments."""
    need(os.environ.get('CUDA_VISIBLE_DEVICES') == '', 'CPU-only document build required')
    root = original.ordinary(root, directory=True)
    before = inspect_sources(root, expected_includes, constants)
    paper = root / 'paper'
    need(not (paper / 'build').exists(), 'Preserve any prior compiled attempt')
    command = ['latexmk', '-pdf', '-bibtex', '-no-shell-escape', '-interaction=nonstopmode',
               '-halt-on-error', '-recorder', '-outdir=build', 'main.tex']
    env = {**os.environ, 'TEXINPUTS': str(paper / 'vendor') + '//:',
           'BSTINPUTS': str(paper / 'vendor') + '//:'}
    result = subprocess.run(command, cwd=paper, env=env, capture_output=True, text=True, timeout=180)
    for name, text in (('compile-stdout.txt', result.stdout), ('compile-stderr.txt', result.stderr)):
        with (root / name).open('x') as stream:
            stream.write(text)
    write_new(root / 'compiler-exited.json', {'exit_code': result.returncode, 'command': command})
    need(result.returncode == 0, 'Actual fresh compiler failed; retain logs')
    build = paper / 'build'
    log = original.ordinary(build / 'main.log').read_text()
    need('Overfull' not in log and not re.search(
        r'(?:Citation|Reference) .+ undefined|There were undefined references', log),
        'Overflow or unresolved reference in actual fresh PDF')
    blg = original.ordinary(build / 'main.blg').read_text()
    require_same(re.findall(r'^Database file #\d+: (.+)$', blg, re.MULTILINE), ['references.bib'])
    require_same(re.findall(r'^The style file: (.+)$', blg, re.MULTILINE), ['acl_natbib.bst'])
    pdf = original.ordinary(build / 'main.pdf')
    def output(tool):
        return subprocess.run([tool, str(pdf)], capture_output=True, text=True, check=True, timeout=30).stdout
    font_text, info = output('pdffonts'), output('pdfinfo')
    pages = re.findall(r'^Pages:\s+(\d+)\s*$', info, re.MULTILINE)
    need(len(pages) == 1, 'Missing current PDF page count')
    fonts = original_build.font_inventory(font_text)
    topology = layout(paper, int(pages[0]))
    inputs = recorded_inputs(paper, original.ordinary(build / 'main.fls').read_text())
    require_same(inputs['document'], {name: before['inputs'][name] for name in TEX_INPUTS})
    require_same(inspect_sources(root, expected_includes, constants), before)
    for path, binding in inputs['system'].items():
        verify_file(path, binding)
    for name, text in (('fonts.txt', font_text), ('pdfinfo.txt', info)):
        with (root / name).open('x') as stream:
            stream.write(text)
    receipt = {'scope': 'current_dense_complete_document_component_v1', 'compiled_pdf_verified': True,
        'source_inspection': before, 'layout': topology, 'font_count': len(fonts),
        'pdf_pages': int(pages[0]), 'compiler_inputs': inputs,
        'upstream_scientific_admission_performed': False, 'final_release_verified': False,
        'artifacts': {p.relative_to(root).as_posix(): file_identity(p) for p in sorted(root.rglob('*')) if p.is_file()}}
    write_new(root / 'document.json', receipt)
    return receipt
