"""Regenerate only the unfinished factorial development placeholder, without scores."""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER = "% Development-only topology fixture."
OUTPUT = Path("paper/generated/state-operator-factorial.tex")


def render_pending() -> str:
    return r"""% Development-only topology fixture.
% Generated by scripts/render_state_operator_pending.py; contains no synthetic scores.
% Only the audited complete-summary renderer may replace these pending findings with results.
\newcommand{\StateOperatorAbstractFinding}{%
\ResultPending{At the 50K continuation endpoint, the state, operator, and interaction contrasts
remain pending. These endpoint contrasts do not decompose the primary-training result.}}
\newcommand{\StateOperatorMechanismFinding}{%
\ResultPending{The averaged source-state contrast, averaged continuation-operator contrast,
and state--operator interaction remain pending, including all three marginal intervals and
decisions. Positive interaction alone would not establish beneficial continuation or
full-trajectory co-adaptation.}}
\newcommand{\StateOperatorConclusionFinding}{%
\ResultPending{The crossed 50K continuation findings remain pending. The design resets optimizer
state and matches the fixed calibration-probe scale; its endpoint contrasts do not decompose
the primary-training result or establish the causal role of a geometric feature.}}
\newcommand{\StateOperatorAppendixTable}{%
\begin{table*}[t]
\centering
\small
\setlength{\tabcolsep}{5pt}
\begin{tabular}{lrrl}
\toprule
Factorial contrast & Effect & Marginal 95\% CI & Decision \\
\midrule
Muon-state $-$ AdamW-state & -- & -- & pending \\
Muon operator $-$ AdamW operator & -- & -- & pending \\
State $\times$ operator interaction & -- & -- & pending \\
\bottomrule
\end{tabular}
\caption{Prospective reset-state factorial. All results remain pending. The three marginal
intervals do not provide simultaneous family-wise coverage.}
\label{tab:state-operator-factorial}
\end{table*}%
}
"""


def write_pending(repository: Path) -> Path:
    repository = repository.resolve()
    output = repository / OUTPUT
    if output.is_symlink() or not output.resolve().is_relative_to(repository):
        raise ValueError("Development placeholder must stay inside the repository")
    report_root = repository / "reports/state-operator-factorial"
    if any(
        (report_root / name).exists()
        for name in ("summary_manifest.json", "publication_manifest.json")
    ):
        raise ValueError("Cannot write a development placeholder after summary/publication exists")
    if output.exists() and not output.read_text().startswith(HEADER):
        raise ValueError("Refuse to replace a non-development factorial include")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_pending(), encoding="utf-8")
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", type=Path, required=True)
    args = parser.parse_args()
    print(write_pending(args.repository))


if __name__ == "__main__":
    main()
