"""Actual native-chain join and in-memory counterexamples; no artifact mutation."""
import copy
import importlib.util
from pathlib import Path
import unittest

spec = importlib.util.spec_from_file_location('tested_current_publication', Path(__file__).with_name('assemble_publication.py'))
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)


class NativeJoin(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from embed_optim.primary_v3_contract import PrimaryV3Contract
        cls.primary = PrimaryV3Contract.load(module.STORY / 'configs/dense_primary_v3_protocol.json', module.STORY, module.PRIMARY)
        # Individual native evidence and payload bindings were generated by real
        # completed consumers. These tests do not replace those native reads.
        cls.actual, cls.bindings = module.native_inputs()

    def test_actual_complete_join(self):
        result = module.join_native(self.primary, self.actual)
        self.assertEqual(result['saved_model_and_seal_joins'], 60)
        self.assertFalse(result['old_single_selection_guard_passed'])

    def reject(self, change):
        value = copy.deepcopy(self.actual)
        change(value)
        with self.assertRaises((ValueError, KeyError)):
            module.join_native(self.primary, value)

    def test_omitted_primary_run(self):
        self.reject(lambda v: v['primary']['grid']['runs'].pop())

    def test_duplicated_geometry_run(self):
        self.reject(lambda v: v['geometry']['original_primary_admission']['rows'].__setitem__(0, v['geometry']['original_primary_admission']['rows'][1]))

    def test_forged_checkpoint_join_hash(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'][0]['model_safetensors'].__setitem__('sha256', '0' * 64))

    def test_forged_checkpoint_seal(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'][0]['checkpoint_seal'].__setitem__('sha256', '0' * 64))

    def test_wrong_stage(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'][0].__setitem__('stage', 99))

    def test_omitted_feature_checkpoint(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'].pop())

    def test_modified_native_deep_state(self):
        self.reject(lambda v: v['primary']['grid']['runs'][0]['deep_checkpoint_checks'][0].__setitem__('parameter_states', 133))

    def test_wrong_source_identity(self):
        self.reject(lambda v: v['primary']['grid']['runs'][0].__setitem__('run_identity_sha256', '0' * 64))


if __name__ == '__main__':
    unittest.main()
