"""Actual native-chain join and in-memory counterexamples; no artifact mutation."""
import copy
import importlib.util
from pathlib import Path
import unittest

spec = importlib.util.spec_from_file_location('tested_current_publication', Path(__file__).with_name('assemble_publication.py'))
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)


class NativeJoin(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from embed_optim.primary_v3_contract import PrimaryV3Contract
        cls.primary = PrimaryV3Contract.load(module.STORY / 'configs/dense_primary_v3_protocol.json', module.STORY, module.PRIMARY)
        # Individual native evidence and payload bindings were generated by real
        # completed consumers. These tests do not replace those native reads.
        cls.actual, cls.bindings = module.native_inputs()

    def test_actual_complete_join(self):
        result = module.join_native(self.primary, self.actual)
        self.assertEqual(result['saved_model_and_seal_joins'], 60)
        self.assertFalse(result['old_single_selection_guard_passed'])

    def reject(self, change):
        value = copy.deepcopy(self.actual)
        change(value)
        with self.assertRaises((ValueError, KeyError)):
            module.join_native(self.primary, value)

    def test_omitted_primary_run(self):
        self.reject(lambda v: v['primary']['grid']['runs'].pop())

    def test_duplicated_geometry_run(self):
        self.reject(lambda v: v['geometry']['original_primary_admission']['rows'].__setitem__(0, v['geometry']['original_primary_admission']['rows'][1]))

    def test_forged_checkpoint_join_hash(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'][0]['model_safetensors'].__setitem__('sha256', '0' * 64))

    def test_forged_checkpoint_seal(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'][0]['checkpoint_seal'].__setitem__('sha256', '0' * 64))

    def test_wrong_stage(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'][0].__setitem__('stage', 99))

    def test_omitted_feature_checkpoint(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'].pop())

    def test_extra_duplicated_feature_checkpoint(self):
        self.reject(lambda v: v['functional']['checkpoint_joins'].append(v['functional']['checkpoint_joins'][0]))

    def test_extra_duplicated_primary_run(self):
        self.reject(lambda v: v['primary']['grid']['runs'].append(v['primary']['grid']['runs'][0]))

    def test_missing_functional_whole_run(self):
        self.reject(lambda v: v['functional']['admitted']['complete_runs'].pop(next(iter(v['functional']['admitted']['complete_runs']))))

    def test_modified_native_deep_state(self):
        self.reject(lambda v: v['primary']['grid']['runs'][0]['deep_checkpoint_checks'][0].__setitem__('parameter_states', 133))

    def test_wrong_source_identity(self):
        self.reject(lambda v: v['primary']['grid']['runs'][0].__setitem__('run_identity_sha256', '0' * 64))

    def test_complete_score_row_reordering_only(self):
        rows = self.actual['primary']['grid']['score_rows']
        ordered = sorted(rows, key=lambda r: (r['run_id'], r['stage'], r['task']))
        module.compare_previous_table(self.primary, 'all_task_scores', ordered, list(reversed(rows)))

    def test_changed_score_is_not_order_difference(self):
        rows = copy.deepcopy(self.actual['primary']['grid']['score_rows'])
        ordered = sorted(rows, key=lambda r: (r['run_id'], r['stage'], r['task']))
        changed = copy.deepcopy(rows)
        changed[0]['ndcg_at_10'] += 0.00001
        with self.assertRaises(ValueError):
            module.compare_previous_table(self.primary, 'all_task_scores', ordered, changed)

    def test_duplicate_score_not_silently_deduplicated(self):
        rows = copy.deepcopy(self.actual['primary']['grid']['score_rows'])
        ordered = sorted(rows, key=lambda r: (r['run_id'], r['stage'], r['task']))
        rows[-1] = rows[0]
        with self.assertRaises(ValueError):
            module.compare_previous_table(self.primary, 'all_task_scores', ordered, rows)

    def test_display_numeric_strings_are_exact(self):
        self.assertEqual(module.compare_display_projection({'a': [50000, 0.125]}, {'a': ['50000', '0.125']}), ['/a/0', '/a/1'])

    def test_display_cast_does_not_hide_number_change(self):
        with self.assertRaises(ValueError):
            module.compare_display_projection(0.125, '0.12500000000000003')

    def test_display_cast_rejects_nonfinite_and_boolean(self):
        for text in ('NaN', 'Infinity', 'true', 'null'):
            with self.subTest(text=text), self.assertRaises(ValueError):
                module.compare_display_projection(1, text)

    def test_display_fields_not_omitted(self):
        with self.assertRaises(ValueError):
            module.compare_display_projection({'a': 1}, {})


if __name__ == '__main__':
    unittest.main()
